cc_binary(
    name = "client",
    srcs = ["client.cc"],
    deps = [
        "//src/user:user",
    ],
)

cc_binary(
    name = "server",
    srcs = ["server.cc"],
    deps = [
        "//config:config",
    ],
)